/*
    Autore: Ignazio Leonardo Calogero Sperandeo
    Data: 11/06/2025
    Consegna: Codice SQL Supplettiva 2015

    by jim-bug // :)
*/

CREATE TABLE TipiMultimediale (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE Centri (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(30) NOT NULL
);

CREATE TABLE Categorie (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(30) NOT NULL UNIQUE,
    Tipologia INT NOT NULL,

    FOREIGN KEY (Tipologia) REFERENCES TipiMultimediale(ID) ON UPDATE CASCADE
);

CREATE TABLE Utenti (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(30) NOT NULL,
    Cognome VARCHAR(30) NOT NULL,
    Data DATE NOT NULL, 
    Username VARCHAR(20) NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Risorse (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(30) NOT NULL,
    Utilizzabile BOOLEAN NOT NULL,
    Categoria INT NOT NULL,
    Centro INT NOT NULL,

    FOREIGN KEY (Categoria) REFERENCES Categorie(ID) ON UPDATE CASCADE
    FOREIGN KEY (Centro) REFERENCES Centri(ID) ON UPDATE CASCADE
);

CREATE TABLE Prestiti (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DataInizio DATE NOT NULL,
    DataFine DATE,
    Utente INT NOT NULL,
    Risorsa INT NOT NULL,

    FOREIGN KEY (Utente) REFERENCES Utenti(ID) ON UPDATE CASCADE
    FOREIGN KEY (Risorsa) REFERENCES Risorse(ID) ON UPDATE CASCADE
);


-- // :)
